- id: '1642128421031'
  alias: Turn off the lights when I leave home
  description: ''
  trigger:
  - platform: state
    entity_id: person.quentin_smith
    from: home
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - bedroom
      - workshop
    data: {}
  mode: single
- id: '1642414403740'
  alias: Turn off lights when setting alarm
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.pixel_4a_5g_next_alarm
    from: unavailable
  condition:
  - condition: state
    entity_id: person.quentin_smith
    state: home
  - condition: time
    after: '22:00:00'
    before: 06:00:00
  action:
  - service: light.turn_off
    target:
      area_id:
      - bedroom
      - workshop
    data:
      transition: 5
  - service: switch.turn_off
    target:
      entity_id:
      - switch.receiver_power
      - switch.tv_power
    data: {}
  mode: single
