---
- ansible.builtin.command: /usr/bin/pacman-key --init
  args:
    creates: /etc/pacman.d/gnupg/gpg.conf
  register: init_keys
- ansible.builtin.lineinfile:
    dest: /etc/pacman.d/gnupg/gpg.conf
    regexp: '^[ #]*keyserver '
    line: keyserver hkps://keyserver.ubuntu.com
- when: init_keys.changed
  block:
  # https://archlinux.org/packages/core/any/archlinux-keyring/download
  # pacman -U archlinux-keyring-20220713-2-any.pkg.tar.zst
  - ansible.builtin.command: /usr/bin/pacman-key --populate
  - ansible.builtin.command: /usr/bin/pacman-key --refresh-keys
- name: check if changes needed
  community.general.pacman:
    name: "{{ (packages + aur_packages) | map('regex_replace', '^.*?/', '') }}"
    state: present
  check_mode: yes
  register: check_packages
- when: check_packages.changed or force_reinstall_packages
  block:
  - ansible.builtin.command: /usr/bin/steamos-readonly disable
    notify: enable readonly
  - community.general.pacman:
      name:
      - archlinux-keyring
      state: latest
      update_cache: yes
  - when: force_reinstall_packages
    ansible.builtin.command: /usr/bin/pacman -S --noconfirm --noprogressbar {{ force_reinstall_packages | join(" ") }}
  - community.general.pacman:
      name: "{{ packages }}"
      state: present
    when: packages
  - yay:
      name: "{{ aur_packages }}"
      state: present
    environment:
      SUDO_USER: deck
    when: aur_packages
