keys:
- &admin_quentin_gpg 1C71A0665400AACD142EB1A004EE05A8FCEFB697
- &server_workshop_ssh_gpg 2b5889b9ad2facafd3e867066bbc96bb384b8c2a
- &server_workshop_ssh_age age1hjrx3z0x257weyxt5u8lcntm6k040e7e4v45y7cz33gs5tmjmu2q4kzc4s
- &server_bedroom-pi_ssh_gpg fdd69b815a8e522631a0aaa477d4571b3a07b63e
- &server_bedroom-pi_ssh_age age1k35dmvna2fe6m47hkxmtuj82pzvxted7fwtvqdek355838vfscesjhyq4q
- &uconsole_ssh_age age19x33srzrvjf9xd5l5zech50gp59yvddzzcutryx0de6uyd8mcfuqftzx3r
- &goddard_ssh_age age1yrgt8wh6pqy49jmgc76e9an6fkztsx448jny5ze694fkvccmreesaelck7
- &heartofgold_ssh_age age1w56w4qlw7hcg68zztjfp9c44nfh4vsaj8xkmqwkxust9gnufjfvq7zhwhu
- &mac_ssh_age age1ssvjqdur387pduhsqvn7cgkxatnxfrjfqf3wnw2eus75zecnsglshzdlrn
- &build-arm_ssh_age age1s0vn6u4zqkz0k5wvagt942er99k3m588gh4vjp7e2lewzkms6asqntknaq

creation_rules:
- path_regex: ^workshop/secrets\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    - *server_workshop_ssh_gpg
    age:
    - *server_workshop_ssh_age
- path_regex: ^bedroom-pi/secrets\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    age:
    - *server_bedroom-pi_ssh_age
- path_regex: ^goddard/secrets\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    age:
    - *goddard_ssh_age
- path_regex: ^heartofgold/secrets\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    age:
    - *heartofgold_ssh_age
- path_regex: ^nix/home/quentin/secrets\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    age:
    - *goddard_ssh_age
    - *mac_ssh_age
- path_regex: ^uconsole/secrets\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    age:
    - *uconsole_ssh_age
- path_regex: ^nix/home/chromium/secrets\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    age:
    - *uconsole_ssh_age
    - *goddard_ssh_age
    - *heartofgold_ssh_age
    - *mac_ssh_age
- path_regex: ^build-arm/secrets\.yaml$
  key_groups:
  - pgp:
    - *admin_quentin_gpg
    age:
    - *build-arm_ssh_age
