{ config, lib, ... }:
{
  networking.nftables.preCheckRuleset = ''
    sed -E 's/skuid \S+/skuid nobody/g; s/socket cgroupv2 level \S+ \S+//g' -i ruleset.conf
  '';
  systemd.services.nginx.serviceConfig.NFTSet = ["cgroup:inet:arr:cg_nginx"];
  networking.nftables.flushRuleset = false;
  networking.nftables.ruleset = ''
    # Flush any existing rules, without disturbing the sets.
    table inet arr;
    flush table inet arr;

    table inet arr {
      set cg_nginx {
        type cgroupsv2
      }
      set cg_arr {
        type cgroupsv2
      }
      chain input {
        # Input hook matches packets about to be delivered to local processes.
        type filter hook input priority filter;
        # Packets about to be delivered to arr
        socket cgroupv2 level 2 @cg_arr jump {
          # Only accept if the connection was already marked.
          ct mark eq 1000 counter accept;
          counter drop;
        }
      }
      chain output {
        # Output hook matches packets generated by local processes.
        type filter hook output priority filter;
        # Packets from nginx should get CT mark 1000
        socket cgroupv2 level 2 @cg_nginx ct mark set 1000 counter;
        # Packets from arr itself should also get CT mark 1000, so replies can be delivered
        socket cgroupv2 level 2 @cg_arr ct mark set 1000 counter;
      }
    }
  '';
}
