all:
  vars:
    ansible_domain: isz.wtf
    #avaya_domain: isz.wtf
    #pki_ca_domain: isz.wtf
    influx_server: influx.{{ ansible_domain }}
    pki_acme_ca: le-live-v2
    pki_acme: yes
    pki_acme_contacts: [ mailto:quentin@mit.edu ]
    #pki_enabled: yes
    pki_internal: no
    pki_download_extra: no
    locales__default_list:
    - en_US.UTF-8
    - en_US
    - en_US.ISO-8859-15
    locales__system_lang: en_US.UTF-8
    mosquitto__allow:
    - 172.30.96.0/24
    - 192.168.88.0/24
    mosquitto__websockets_packages:
    - libwebsockets16
    mosquitto__pki_broker_realm: '{{ mosquitto__fqdn }}'
    mosquitto__nginx_extra_config:
      pki_realm: '{{ mosquitto__fqdn }}'
      hsts_enabled: false
      redirect_to_ssl: false
    nullmailer__adminaddr: quentin@isz.wtf
    nullmailer__default_remotes:
    - '{{ smtp2go_remote }}'
    nullmailer__allmailfrom: 'root@{{ nullmailer__domain }}'
  hosts:
    workshop-pi.isz.wtf:
      isz_last_octet: 32
      macaddress: dc:a6:32:d3:49:0c
      ansible_processor_cores: 4
      ansible_processor_vcpus: 4
    bedroom-pi.isz.wtf:
    heartofgold.isz.wtf:
    workshop.isz.wtf:
      isz_last_octet: 34
      macaddress: 04:42:1A:C9:93:8B
    steamdeck.isz.wtf:
      isz_last_octet: 102
      macaddress: 2C:3B:70:EF:B6:6D
      telegraf_id: 0a30c4552f055000
