version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin:unstable
    container_name: jellyfin
    network_mode: host
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /srv/media:/media
    restart: unless-stopped
  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: telegraf.env
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    network_mode: host
    privileged: yes
    entrypoint:
      - /entrypoint.sh
      - telegraf
      - --config
      - http://influx.isz.wtf:8086/api/v2/telegrafs/06f519251454e000
    restart: always
