version: '3.4'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    command: dashboard --address=127.0.0.1 /config
    env_file: esphome.env
    volumes:
      - /srv/isz/workshop/esphome:/config
    network_mode: host
  atuin:
    container_name: atuin
    image: ellieh/atuin
    build:
      context: atuin
    volumes:
      - /srv/isz/workshop/atuin-server.toml:/config/server.toml
    command: server start
  freepbx-app:
    container_name: freepbx-app
    image: epandi/asterisk-freepbx-arm:18.15-alpha
    ports:
    #### If you aren't using a reverse proxy
    #- 80:80
    #### If you want SSL Support and not using a reverse proxy
    #- 443:443
    - 5060:5060/tcp
    - 5060:5060/udp
    - 5160:5160/tcp
    - 5160:5160/udp
    - 18000-18100:18000-18100/udp
    #### Flash Operator Panel
    - 4445:4445
    volumes:
    - /srv/freepbx/certs:/certs
    - /srv/freepbx/data:/data
    - /srv/freepbx/logs:/var/log
    - /srv/freepbx/data/www:/var/www/html
    ### Only Enable this option below if you set DB_EMBEDDED=TRUE
    - /srv/freepbx/db:/var/lib/mysql
    ### You can drop custom files overtop of the image if you have made modifications to modules/css/whatever - Use with care
    #- ./assets/custom:/assets/custom

    environment:
    - VIRTUAL_HOST=pbx.isz.wtf
    - VIRTUAL_NETWORK=nginx-proxy
    ### If you want to connect to the SSL Enabled Container
    #- VIRTUAL_PORT=443
    #- VIRTUAL_PROTO=https
    - VIRTUAL_PORT=80
    #- LETSENCRYPT_HOST=hostname.example.com
    #- LETSENCRYPT_EMAIL=email@example.com

    - ENABLE_ZABBIX=FALSE
    - ENABLE_FAIL2BAN=FALSE

    - RTP_START=18000
    - RTP_FINISH=18100

    ## Use for External MySQL Server
    - DB_EMBEDDED=TRUE

    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.100

networks:
  default:
    ipam:
      config:
      - subnet: 172.18.0.0/24
