version: '3.4'
services:
  influxdb:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:nightly
    ports:
      - "172.30.97.32:8086:8086"
      - "172.30.96.32:8086:8086"
    volumes:
      - /srv/influxdb/etc:/etc/influxdbv2
      - /srv/influxdb/data:/influxdbv2
    environment:
      - TZ=America/New_York
      - INFLUXD_CONFIG_PATH
      - INFLUXD_BOLT_PATH=/influxdbv2/influxd.bolt
      - INFLUXD_ENGINE_PATH=/influxdbv2/engine
      - INFLUXD_REPORTING_DISABLED=true
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana:dev
    ports:
      - "172.30.97.32:3000:3000"
      - "172.30.96.32:3000:3000"
    volumes:
      - /srv/influxdb/grafana-storage:/var/lib/grafana
    restart: always
  pwrgate-logger:
    build:
      context: go
      target: pwrgate-logger
    environment:
      - INFLUX_SERVER=http://influxdb:8086/
    env_file: logger.env
    devices:
      - "/dev/ttyPwrgate:/dev/ttyACM0"
    restart: always
  linkzone-logger:
    build:
      context: go
      target: linkzone-logger
    hostname: workshop-pi.isz
    env_file: logger.env
    environment:
      - INFLUX_SERVER=http://influxdb:8086/
    restart: always
  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: telegraf.env
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    network_mode: host
    entrypoint:
      - /entrypoint.sh
      - telegraf
      - --config
      - http://172.30.97.32:8086/api/v2/telegrafs/0702075a793e0000
    restart: always
  speedtest:
    restart: always
    build: speedtest
    links:
      - "influxdb:influxdb"
    env_file: speedtest.env
    environment:
      - "INTERVAL=3600"
      - "SHOW_EXTERNAL_IP=true"
      - "INFLUXDB_DB=speedtest"
      - "INFLUXDB_USER=speedtest"
      - "INCLUDE_READABLE_OUTPUT=true"
#      - "SPEEDTEST_LIST_SERVERS=true"
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/isz/workshop/homeassistant:/config
    devices:
      - "/dev/ttyZwave:/dev/ttyZwave"
    network_mode: host
  esphome:
    container_name: esphome
    image: esphome/esphome
    command: dashboard --address=127.0.0.1 /config
    env_file: esphome.env
    volumes:
      - /srv/isz/workshop/esphome:/config
    network_mode: host
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    ports:
      - 8091:8091
      - 3001:3001
    devices:
      - "/dev/ttyZwave:/dev/ttyZwave"
    volumes:
      - /srv/isz/workshop/zwavejs2mqtt:/usr/src/app/store
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    env_file: postgres.env
    volumes:
      - /srv/postgresql/data:/var/lib/postgresql/data
  atuin:
    container_name: atuin
    image: ellieh/atuin
    build:
      context: atuin
    volumes:
      - /srv/isz/workshop/atuin-server.toml:/config/server.toml
    command: server start
  freepbx-app:
    container_name: freepbx-app
    image: epandi/asterisk-freepbx-arm:18.15-alpha
    ports:
    #### If you aren't using a reverse proxy
    #- 80:80
    #### If you want SSL Support and not using a reverse proxy
    #- 443:443
    - 5060:5060/tcp
    - 5060:5060/udp
    - 5160:5160/tcp
    - 5160:5160/udp
    - 18000-18100:18000-18100/udp
    #### Flash Operator Panel
    - 4445:4445
    volumes:
    - /srv/freepbx/certs:/certs
    - /srv/freepbx/data:/data
    - /srv/freepbx/logs:/var/log
    - /srv/freepbx/data/www:/var/www/html
    ### Only Enable this option below if you set DB_EMBEDDED=TRUE
    - /srv/freepbx/db:/var/lib/mysql
    ### You can drop custom files overtop of the image if you have made modifications to modules/css/whatever - Use with care
    #- ./assets/custom:/assets/custom

    environment:
    - VIRTUAL_HOST=pbx.isz.wtf
    - VIRTUAL_NETWORK=nginx-proxy
    ### If you want to connect to the SSL Enabled Container
    #- VIRTUAL_PORT=443
    #- VIRTUAL_PROTO=https
    - VIRTUAL_PORT=80
    #- LETSENCRYPT_HOST=hostname.example.com
    #- LETSENCRYPT_EMAIL=email@example.com

    - ENABLE_ZABBIX=FALSE
    - ENABLE_FAIL2BAN=FALSE

    - RTP_START=18000
    - RTP_FINISH=18100

    ## Use for External MySQL Server
    - DB_EMBEDDED=TRUE

    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.100

networks:
  default:
    ipam:
      config:
      - subnet: 172.18.0.0/24
