

button:

- platform: template
  name: Living Room AC - sleep
  id: ir_living_room_ac_sleep
  icon: mdi:power-sleep
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xFF00


- platform: template
  name: Living Room AC - fan+
  id: ir_living_room_ac_fan_up
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xFE01


- platform: template
  name: Living Room AC - mode esave
  id: ir_living_room_ac_mode_esave
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xFD02


- platform: template
  name: Living Room AC - fan-
  id: ir_living_room_ac_fan_down
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xFB04


- platform: template
  name: Living Room AC - timer
  id: ir_living_room_ac_timer
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xF906


- platform: template
  name: Living Room AC - mode fan
  id: ir_living_room_ac_mode_fan
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xF807


- platform: template
  name: Living Room AC - mode cool
  id: ir_living_room_ac_mode_cool
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xF609


- platform: template
  name: Living Room AC - temp-
  id: ir_living_room_ac_temp_down
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xF20D


- platform: template
  name: Living Room AC - temp+
  id: ir_living_room_ac_temp_up
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xF10E


- platform: template
  name: Living Room AC - fan auto
  id: ir_living_room_ac_fan_auto
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xF00F


- platform: template
  name: Living Room AC - power
  id: ir_living_room_ac_power
  icon: mdi:power
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0xEE11


- platform: template
  name: Living Room AC - remote sensing start
  id: ir_living_room_ac_remote_sensing_start
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0x50AF


- platform: template
  name: Living Room AC - remote sensing stop
  id: ir_living_room_ac_remote_sensing_stop
  on_press:
    then:
    - remote_transmitter.transmit_nec:
        address: 0xF508
        command: 0x10EF


