---
- name: Install utilities
  package:
    name:
    - acpica-tools
    - apt-file
    - bash-completion
    - bsdmainutils
    - bind9-host
    - bwm-ng
    - command-not-found
    - cpuset
    - curl
    - debsums
    - emacs-nox
    - exfat-utils
    - fping
    #- glances
    - htop
    - info
    - ionit
    - iotop
    - jq
    - lsof
    - man-db
    - mlocate
    - mtr-tiny
    - ncdu
    - netcat
    - nmap
    #- rfkill
    - rsync
    - screen
    - socat
    - sqlite3
    - strace
    - sysstat
    - telnet
    - tree
    - tshark
    - usbutils
    - v4l-utils
    - wget
- command: update-command-not-found
  args:
    creates: /var/lib/command-not-found/commands.db
- package:
    name:
    - bridge-utils
    - certbot
    - docker-compose
    - docker.io
    - fbset
    - ffmpeg
    - golang
    - i2c-tools
    - iptables
    - lm-sensors
    - net-tools
    - podman
    - python3-venv
    - snmp
    - snmp-mibs-downloader
    - vlan
    - wireless-regdb
    - wireless-tools
- package:
    name:
    - device-tree-compiler
    #- raspberrypi-kernel
  when: ansible_architecture == "aarch64"
- blockinfile:
    path: /root/.bashrc
    block: |
      export PATH=/root/go/bin:$PATH

      export HISTSIZE=100000
- file:
    path: /root/.config/git
    state: directory
- copy:
    dest: /root/.config/git/ignore
    content: |
      *~
- copy:
    dest: /root/.emacs
    content: |
      (require 'package)
      (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
      (package-initialize)
      (custom-set-variables
       ;; custom-set-variables was added by Custom.
       ;; If you edit it by hand, you could mess it up, so be careful.
       ;; Your init file should contain only one such instance.
       ;; If there is more than one, they won't work right.
       '(gofmt-command "goimports")
       '(ido-mode (quote both) nil (ido))
       '(package-selected-packages (quote (dockerfile-mode go-mode yaml-mode))))
      (custom-set-faces
       ;; custom-set-faces was added by Custom.
       ;; If you edit it by hand, you could mess it up, so be careful.
       ;; Your init file should contain only one such instance.
       ;; If there is more than one, they won't work right.
       )
      (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
      (defun go-mode-setup ()
       ;(go-eldoc-setup)
       (add-hook 'before-save-hook 'gofmt-before-save))
      (add-hook 'go-mode-hook 'go-mode-setup)
    
- copy:
    dest: /root/.gitconfig
    content: |
      # This is Git's per-user configuration file.
      [user]
      # Please adapt and uncomment the following lines:
              name = Quentin Smith
              email = quentin@mit.edu
      [alias]
              up = pull --rebase
              k = log --graph --abbrev-commit --pretty=oneline --decorate
