esphome:
  name: bedroom-lights

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .guest.isz.wtf

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Lights Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal bedroom-lights"
    update_interval: 60s

output:
  - platform: esp8266_pwm
    pin: 15
    frequency: 250 Hz
    id: pwm_r
    min_power: 0.0005
    zero_means_zero: true
  - platform: esp8266_pwm
    pin: 13
    frequency: 250 Hz
    id: pwm_g
    min_power: 0.0005
    zero_means_zero: true
#  - platform: esp8266_pwm
#    pin: 12
#    frequency: 1000 Hz
#    id: pwm_b
#  - platform: esp8266_pwm
#    pin: 14
#    frequency: 1000 Hz
#    id: pwm_w1
#  - platform: esp8266_pwm
#    pin: 4
#    frequency: 1000 Hz
#    id: pwm_w2

light:
  - platform: monochromatic
    id: headboard
    name: "Headboard"
    output: pwm_r
  - platform: monochromatic
    id: underlight_l
    name: "Underlight L"
    output: pwm_g
