esphome:
  name: inkplate6plus

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .guest.isz.wtf

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Inkplate6Plus Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

switch:
  - platform: restart
    name: "Inkplate Reboot"
    id: reboot

  - platform: gpio
    id: battery_read_mosfet
    pin:
      mcp23xxx: mcp23017_hub
      number: 9
      inverted: true
    restore_mode: ALWAYS_OFF

  - platform: template
    name: "Inkplate Greyscale mode"
    lambda: return id(inkplate_display).get_greyscale();
    turn_on_action:
      - lambda: id(inkplate_display).set_greyscale(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_greyscale(false);

  - platform: template
    name: "Inkplate Partial Updating"
    lambda: return id(inkplate_display).get_partial_updating();
    turn_on_action:
      - lambda: id(inkplate_display).set_partial_updating(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_partial_updating(false);

  - platform: gpio
    id: touchscreen_enable
    restore_mode: ALWAYS_ON
    pin:
      mcp23xxx: mcp23017_hub
      number: 12
      inverted: true
      
sensor:
  - platform: adc
    id: battery_voltage
    update_interval: never
    attenuation: 11db
    pin: 35
  - platform: template
    name: "Inkplate Battery Voltage"
    lambda: |-
      id(battery_read_mosfet).turn_on();
      delay(1);
      float adc = id(battery_voltage).sample();
      id(battery_read_mosfet).turn_off();
      return adc;
    filters:
      - multiply: 2
  - platform: homeassistant
    entity_id: weather.accuweather
    attribute: temperature
    id: weather_temp
  - platform: homeassistant
    name: "Forecast Low"
    entity_id: sensor.accuweather_temperature_min_0d
    id: weather_temp_low
    internal: true
  - platform: homeassistant
    name: "Forecast High"
    entity_id: sensor.accuweather_temperature_max_0d
    id: weather_temp_high
    internal: true
  - platform: homeassistant
    entity_id: sensor.workshop_temperature
    id: workshop_temp
  - platform: homeassistant
    entity_id: sensor.outdoor_temperature
    id: outdoor_temp
  - platform: homeassistant
    entity_id: sensor.bedroom_bed_temperature
    id: bedroom_bed_temp

text_sensor:
- platform: homeassistant
  name: "Moon Phase"
  entity_id: sensor.moon
  id: moon_phase
  internal: true
- platform: homeassistant
  name: "Weather Icon"
  entity_id: weather.accuweather
  id: weather_icon
  internal: true
- platform: homeassistant
  entity_id: sensor.sunrise_text
  id: sunrise
  internal: true
- platform: homeassistant
  entity_id: sensor.sunset_text
  id: sunset
  internal: true

light:
- platform: monochromatic
  id: backlight
  name: "Inkplate Backlight"
  output: backlight_level
  on_turn_on:
    then:
    - output.turn_on: backlight_enable
  on_turn_off:
    - output.turn_off: backlight_enable

i2c:

mcp23017:
  - id: mcp23017_hub
    address: 0x20

output:
  - platform: gpio
    id: backlight_enable
    pin:
      mcp23xxx: mcp23017_hub
      number: 11
  - platform: mcp47a1
    id: backlight_level

binary_sensor:
  - platform: status
    name: "Inkplate Status"
    id: system_status
    
time:
  - platform: sntp
    id: esptime
    
font:
  - file: "fonts/Helvetica.ttf"
    id: helvetica_96
    size: 96
  - file: "fonts/Helvetica.ttf"
    id: helvetica_48
    size: 48

display:
- platform: inkplate6
  id: inkplate_display
  greyscale: false
  partial_updating: false
  update_interval: 60s
  model: inkplate_6_plus

  ckv_pin: 32
  sph_pin: 33
  gmod_pin:
    mcp23xxx: mcp23017_hub
    number: 1
  gpio0_enable_pin:
    mcp23xxx: mcp23017_hub
    number: 8
  oe_pin:
    mcp23xxx: mcp23017_hub
    number: 0
  spv_pin:
    mcp23xxx: mcp23017_hub
    number: 2
  powerup_pin:
    mcp23xxx: mcp23017_hub
    number: 4
  wakeup_pin:
    mcp23xxx: mcp23017_hub
    number: 3
  vcom_pin:
    mcp23xxx: mcp23017_hub
    number: 5
    
    
  lambda: |-
    it.fill(COLOR_ON);

    it.print(100, 100, id(helvetica_48), COLOR_OFF, TextAlign::TOP_LEFT, "ESPHome");

    it.strftime(400, 300, id(helvetica_48), COLOR_OFF, TextAlign::CENTER, "%Y-%m-%d", id(esptime).now());
    it.strftime(400, 400, id(helvetica_96), COLOR_OFF, TextAlign::CENTER, "%H:%M", id(esptime).now());

    if (id(system_status).state) {
      it.print(700, 100, id(helvetica_48), COLOR_OFF, TextAlign::TOP_RIGHT, "Online");
    } else {
      it.print(700, 100, id(helvetica_48), COLOR_OFF, TextAlign::TOP_RIGHT, "Offline");
    }
