# Pin configuration:
# 6 - WifiLED_n
# 7 - Relay
# 8 - Button

substitutions:
  name: livingroom-traintrackr-power
  friendly_name: Traintrackr Power

bk72xx:
  board: cbu

packages:
  isz_base: !include include/isz-base.yaml

# Enable logging
logger:
  hardware_uart: UART1

status_led:
  pin:
    number: 6
    inverted: yes

switch:
- platform: gpio
  id: power
  name: ""
  pin: 7

binary_sensor:
- platform: gpio
  id: front_button
  name: Button
  pin:
    number: 8
    mode:
      input: true
      pullup: true
