# GPIO 0 - Red LED, active low
# GPIO 1 - "RX" (UART0 TX) / 1-Wire
# GPIO 2 - Blue LED, active low
# GPIO 3 - "TX" (UART0 RX) / IR LED
# GPIO 4 - Relay output, active high
# GPIO 5 - Power monitoring CF pin
# GPIO 12 - Power monitoring SEL pin
# GPIO 13 - Button input, requires pullup R
# GPIO 14 - Power monitoring CF1 pin
# GPIO 15 - ??? (3.2V, resistor pulldown to ground)

# Module pinout
# Voltage sense?
# Current sense -
# Current sense +
# Gnd / 1.5V?
# GPIO 15 / RST?
# GPIO 1 "RX" / GPIO 3 "TX"
# GPIO 13 button / GPIO 2 blue LED
# 3.3V? / GPIO 4 relay
# GPIO 0 red LED / Vcc 3.3V


substitutions:
  name: livingroom-ac
packages:
  kauf.plf10: github://KaufHA/PLF10/kauf-plug.yaml
esphome:
  name_add_mac_suffix: false
logger:
  # Disable UART logging so we can reuse the pins.
  baud_rate: 0

# voltage scale: 101.5%

remote_transmitter:
  pin: GPIO3
  carrier_duty_percent: 50%

dallas:
- pin: GPIO1

sensor:
- platform: dallas
  address: 0x6600000284ba8b28
  name: Living Room AC Temperature

button:
- platform: template
  name: AC Power
  on_press:
  - remote_transmitter.transmit_nec:
      address: 0xF508
      command: 0xEE11

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
