# Pin configuration:
# 6 - WifiLED_n
# 7 - Relay
# 8 - Button

substitutions:
  name: livingroom-traintrackr-power
  friendly_name: Traintrackr Power

bk72xx:
  board: cbu

packages:
  isz_base: !include include/isz-base.yaml

# Enable logging
logger:
  hardware_uart: UART1

light:
  - platform: status_led
    name: Status LED
    id: status
    entity_category: diagnostic
    pin:
      number: 6

esphome:
  on_boot:
  - priority: -100
    then:
    - light.control:
        id: status
        state: !lambda return id(power).state;

switch:
- platform: gpio
  id: power
  name: ""
  pin: 7
  restore_mode: ALWAYS_ON
  on_state:
  - light.control:
      id: status
      state: !lambda return x;

binary_sensor:
- platform: gpio
  id: front_button
  name: Button
  pin:
    number: 8
    mode:
      input: true
      pullup: true
    inverted: true
  on_click:
  - switch.toggle:
      id: power
