- hosts: all
  serial: 1
  tasks:
  - package:
      name:
      - bc
      - bison
      - flex
      - libssl-dev
# git clone https://github.com/raspberrypi/linux.git
  - ansible.builtin.git:
      repo: https://github.com/raspberrypi/linux.git
      dest: /root/linux
# cd linux
# make bcm2711_defconfig
  - command: make bcm2711_defconfig
    args:
      chdir: /root/linux
  - ini_file:
      path: /root/linux/.config
      section: null
      no_extra_spaces: yes
      option: "{{ item.key }}"
      value: "{{ item.valu }}"
    with_dict:
      # scripts/config --enable CONFIG_BRIDGE_VLAN_FILTERING
      CONFIG_BRIDGE_VLAN_FILTERING: y
      # scripts/config --set-str CONFIG_LOCALVERSION $(scripts/config --state CONFIG_LOCALVERSION)-isz
      CONFIG_LOCALVERSION: "-v8-isz"
      # scripts/config --disable DEBUG_INFO
      CONFIG_DEBUG_INFO: n
  # sed -i '/KBUILD_IMAGE/ s/.gz//' arch/arm64/Makefile
  - lineinfile:
      path: /root/linux/arch/arm64/Makefile
      regexp: '^(KBUILD_IMAGE.*?)(\.gz)?$'
      line: '\1'
      backrefs: yes
  # make -j `nproc` bindeb-pkg
  - command: "make -j $(nproc) bindeb-pkg"
    args:
      chdir: /root/linux
