- hosts: all
  serial: 1
  environment: '{{ inventory__environment | d({})
  | combine(inventory__group_environment | d({}))
  | combine(inventory__host_environment  | d({})) }}'
  roles:
  - role: debops.debops.etckeeper
    when: ansible_os_family == 'Debian'
  - role: debops.debops.core
    tags: [ 'role::core', 'skip::core' ]
  tasks:
    - name: Install playbook Python dependencies
      package:
        name:
          - python3-netaddr
          #- python3-dns{{ "python" if ansible_os_family == "Debian" else "" }}
        state: present
      when: ansible_connection == 'local'

- import_playbook: workshop.yml
- import_playbook: steamdeck.yml
