- hosts:
  - steamdeck.isz.wtf
  serial: 1
  vars:
    telegraf_config_url: https://influx.{{ansible_domain}}/api/v2/telegrafs/{{telegraf_id}}
  tasks:
  - name: Disable password logins over SSH
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^[ #]*PasswordAuthentication '
      line: PasswordAuthentication no
    notify: reload sshd
  - ansible.builtin.systemd:
      name: sshd
      enabled: yes
      state: started
  # TODO: Consider enabling lingering (KillUserProcesses=no)
  - community.general.flatpak:
      name:
      # Network apps
      - com.discordapp.Discord
      - com.github.fries1234.ncsa-mosaic
      - com.google.Chrome
      - com.github.unrud.RemoteTouchpad
      - com.github.iwalton3.jellyfin-media-player
      - de.shorsh.discord-screenaudio
      - io.freetubeapp.FreeTube
      - org.mozilla.firefox
      - org.signal.Signal
      - uk.org.greenend.chiark.sgtatham.putty
      # Productivity
      - ch.theologeek.Manuskript
      - org.libreoffice.LibreOffice
      # Graphics
      - com.boxy_svg.BoxySVG
      # Games
      - com.github.k4zmu2a.spacecadetpinball
      - com.heroicgameslauncher.hgl
      - io.openrct2.OpenRCT2
      - net.sourceforge.ExtremeTuxRacer
      - net.supertuxkart.SuperTuxKart
      - org.libretro.RetroArch
      - com.steamgriddb.steam-rom-manager
      - io.github.dosbox-staging
      - org.duckstation.DuckStation
      - app.xemu.xemu
      - org.scummvm.ScummVM
      - org.yuzu_emu.yuzu
      - net._86box._86Box
      - net.brinkervii.grapejuice
      - net.cebix.basilisk
      - org.kde.kstars
      - org.stellarium.Stellarium
      - io.github.shiiion.primehack
      - com.steamdeckrepo.manager
      - net.rpcs3.RPCS3
      - org.citra_emu.citra
      - org.DolphinEmu.dolphin-emu
      - org.ppsspp.PPSSPP
      # Development
      - com.github.tchx84.Flatseal
      - com.visualstudio.code.insiders # flathub-beta
      - io.github.shiftey.Desktop
      - org.gnu.emacs
      - com.github.treagod.spectator
      - com.google.AndroidStudio
      - org.fritzing.Fritzing
      - re.sonny.Playhouse
      # Multimedia
      - com.obsproject.Studio
      #- com.obsproject.Studio.Plugin.InputOverlay
      # Radio
      - info.mumble.Mumble
      # Utilities
      - com.whitemagicsoftware.kmcaster
      - org.linux_hardware.hw-probe
      - net.davidotek.pupgui2
      - com.steamgriddb.SGDBoop
      - io.qt.qdbusviewer
      - io.github.arunsivaramanneo.GPUViewer
      - org.bluesabre.MenuLibre
      - org.gnome.dspy
      method: system
  - ansible.builtin.command: pacman -Qk {{ packages | join(' ') }}
    check_mode: no
    register: missing_files
    changed_when: no
    failed_when: missing_files.rc > 1
    vars:
      packages:
      - clang
      - gcc
      - gcc-libs
      - glibc
      - lib32-glibc
      - linux-api-headers
      - systemd
      - systemd-swap
      - systemd-sysvcompat
  # TODO: --overwrite needed for /etc/ld.so.conf.d/fakeroot.conf
  - ansible.builtin.lineinfile:
      name: /etc/pacman.conf
      line: "[holo-beta]"
      state: present
    check_mode: yes
    register: holo_beta
  - ansible.builtin.set_fact:
      holo_repo: "{{ 'holo-rel' if holo_beta is changed else 'holo-beta' }}"
  - ansible.builtin.include_role:
      name: steamdeck-pacman
    tags: [ pacman ]
    vars:
      packages:
      - base-devel
      - "{{ holo_repo }}/linux-headers"
      - linux-neptune-headers
      - "{{ holo_repo }}/linux-lts-headers"
      # Other packages to consider from
      # https://www.reddit.com/r/SteamDeck/comments/t92ozw/comment/i8qxemd/?utm_source=share&utm_medium=web2x&context=3
      # tmux git podman yay-git mlocate
      - fingerterm
      - qt5-xmlpatterns # missing dependency of fingerterm
      - python-pyqt5
      #- wayvnc # gpg error
      aur_packages:
      - telegraf-bin
      force_reinstall_packages: '{{ missing_files.stdout_lines | reject("match", ".* 0 missing files") | map("split", ":") | map("first") }}'
  - ansible.builtin.include_role:
      name: steamdeck-telegraf
  # TODO: Install Decky Loader
  handlers:
  - name: reload systemd
    ansible.builtin.systemd:
      daemon_reload: yes
  - name: reload sshd
    ansible.builtin.service:
      name: sshd
      state: reloaded
