- hosts:
  - steamdeck.isz.wtf
  serial: 1
  vars:
    telegraf_config_url: https://influx.{{ansible_domain}}/api/v2/telegrafs/{{telegraf_id}}
  tasks:
  - name: Disable password logins over SSH
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^[ #]*PasswordAuthentication '
      line: PasswordAuthentication no
    notify: reload sshd
  - ansible.builtin.systemd:
      name: sshd
      enabled: yes
      state: started
  # TODO: Consider enabling lingering (KillUserProcesses=no)
  - community.general.flatpak:
      name:
      # Network apps
      - com.discordapp.Discord
      - com.github.fries1234.ncsa-mosaic
      - com.google.Chrome
      - com.github.unrud.RemoteTouchpad
      - com.github.iwalton3.jellyfin-media-player
      - de.shorsh.discord-screenaudio
      - me.kozec.syncthingtk
      - io.freetubeapp.FreeTube
      - org.netsurf_browser.NetSurf
      - org.qgis.qgis
      - org.remmina.Remmina
      - org.mozilla.firefox
      - org.signal.Signal
      - org.wireshark.Wireshark
      - uk.org.greenend.chiark.sgtatham.putty
      # Graphics
      - com.boxy_svg.BoxySVG
      - net.scribus.Scribus
      - org.darktable.Darktable
      - org.freecadweb.FreeCAD
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.kde.krita
      - org.kde.digikam
      # Games
      - com.github.k4zmu2a.spacecadetpinball
      - com.heroicgameslauncher.hgl
      - io.openrct2.OpenRCT2
      - net.sourceforge.ExtremeTuxRacer
      - net.supertuxkart.SuperTuxKart
      - org.libretro.RetroArch
      - com.steamgriddb.steam-rom-manager
      - com.dosbox.DOSBox
      - io.github.dosbox-staging
      - org.duckstation.DuckStation
      - app.xemu.xemu
      - org.scummvm.ScummVM
      - org.yuzu_emu.yuzu
      - net._86box._86Box
      - net.brinkervii.grapejuice
      - net.cebix.basilisk
      - org.kde.kstars
      - org.stellarium.Stellarium
      # Development
      - com.github.tchx84.Flatseal
      - com.visualstudio.code.insiders # flathub-beta
      - io.github.shiftey.Desktop
      - org.gnu.emacs
      - org.ghidra_sre.Ghidra
      - com.github.treagod.spectator
      - com.gitlab.cutecom.cutecom
      - com.google.AndroidStudio
      - org.fritzing.Fritzing
      - org.radare.iaito
      # Multimedia
      - com.obsproject.Studio
      #- com.obsproject.Studio.Plugin.InputOverlay
      - org.videolan.VLC
      - fr.natron.Natron
      - com.github.wwmm.easyeffects
      - org.pipewire.Helvum
      - org.rncbc.qpwgraph
      - net.sourceforge.VMPK
      - org.kde.kdenlive
      # Radio
      - com.w1hkj.fldigi
      - com.w1hkj.flrig
      - net.oz9aec.Gpredict
      - be.telenet.user.QSSTV
      - info.mumble.Mumble
      - org.sdrangel.SDRangel
      - org.viking.Viking
      # Utilities
      - com.whitemagicsoftware.kmcaster
      - org.cubocore.CoreKeyboard
      - org.linux_hardware.hw-probe
      - net.davidotek.pupgui2
      - com.usebottles.bottles
      - com.steamgriddb.SGDBoop
      - com.dosbox.DOSBox
      - org.kde.kwalletmanager5
      - com.github.donadigo.appeditor
      - io.gitlab.jstest_gtk.jstest_gtk
      - io.qt.qdbusviewer
      method: system
  - ansible.builtin.command: pacman -Qk {{ packages | join(' ') }}
    check_mode: no
    register: missing_files
    changed_when: no
    failed_when: missing_files.rc > 1
    vars:
      packages:
      - clang
      - gcc
      - gcc-libs
      - glibc
      - lib32-glibc
      - linux-api-headers
      - systemd
      - systemd-swap
      - systemd-sysvcompat
  # TODO: --overwrite needed for /etc/ld.so.conf.d/fakeroot.conf
  - ansible.builtin.include_role:
      name: steamdeck-pacman
    tags: [ pacman ]
    vars:
      packages:
      - base-devel
      - git-lfs
      - cmake
      - htop
      - wget
      - ncdu
      - holo/linux-headers
      - linux-neptune-headers
      - holo/linux-lts-headers
      # Other packages to consider from
      # https://www.reddit.com/r/SteamDeck/comments/t92ozw/comment/i8qxemd/?utm_source=share&utm_medium=web2x&context=3
      # tmux git podman yay-git mlocate
      - onboard
      - fingerterm
      - qt5-xmlpatterns # missing dependency of fingerterm
      - dosbox
      - inotify-tools
      - timidity++
      - python-pyqt5
      #- mosh # perl-io-tty is uninstallable because gpg error
      - gnu-netcat
      - x11vnc # gpg error
      #- wayvnc # gpg error
      aur_packages:
      - telegraf-bin
      force_reinstall_packages: '{{ missing_files.stdout_lines | reject("match", ".* 0 missing files") | map("split", ":") | map("first") }}'
  - ansible.builtin.include_role:
      name: steamdeck-telegraf
  # TODO: Install Decky Loader
  handlers:
  - name: reload systemd
    ansible.builtin.systemd:
      daemon_reload: yes
  - name: reload sshd
    ansible.builtin.service:
      name: sshd
      state: reloaded
