# TODO: Create quentin user
# TODO: Install RPi kernel and make w1 work
- hosts:
  - workshop.isz.wtf
  serial: 1
  vars:
    nginx_hsts_age: '{{ 60 * 60 }}'
    nginx_hsts_subdomains: False
  roles:
  - role: avaya
    tags: [ 'role::avaya', 'skip::avaya' ]
